{"level": "DEBUG", "message": "debug message", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "acdc": "sample line"}
{"level": "INFO", "message": "info message", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message: division by zero\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-04-21T01:53:44.761723+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 25, "thread_name": "MainThread", "acdc": "sample line"}
{"level": "INFO", "message": "info message", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 26, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 27, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main.py\", line 32, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-04-21T01:55:19.373524+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 34, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread", "acdc": "sample line"}
{"level": "INFO", "message": "info message", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 32, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main.py\", line 35, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-04-21T01:59:52.629819+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 37, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-04-21T02:00:18.448997+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 28, "thread_name": "MainThread", "acdc": "sample line"}
{"level": "INFO", "message": "info message", "timestamp": "2025-04-21T02:00:18.448997+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-04-21T02:00:18.449534+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-04-21T02:00:18.449534+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-04-21T02:00:18.449534+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 32, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main.py\", line 35, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-04-21T02:00:18.449534+00:00", "logger": "__main__", "module": "main", "function": "main", "line": 37, "thread_name": "MainThread"}
{"level": "DEBUG", "message": "debug message", "timestamp": "2025-04-21T02:01:27.513436+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 28, "thread_name": "MainThread", "acdc": "sample line"}
{"level": "INFO", "message": "info message", "timestamp": "2025-04-21T02:01:27.514415+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 29, "thread_name": "MainThread"}
{"level": "WARNING", "message": "warning message", "timestamp": "2025-04-21T02:01:27.514415+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 30, "thread_name": "MainThread"}
{"level": "ERROR", "message": "error message", "timestamp": "2025-04-21T02:01:27.514415+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 31, "thread_name": "MainThread"}
{"level": "CRITICAL", "message": "critical message", "timestamp": "2025-04-21T02:01:27.514415+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 32, "thread_name": "MainThread"}
{"level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main_copy.py\", line 35, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "timestamp": "2025-04-21T02:01:27.514415+00:00", "logger": "__main__", "module": "main_copy", "function": "main", "line": 37, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "DEBUG", "message": "debug message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 28, "thread_name": "MainThread", "acdc": "sample line"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "INFO", "message": "info message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 29, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "WARNING", "message": "warning message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 30, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "ERROR", "message": "error message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 31, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "CRITICAL", "message": "critical message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 32, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:05:25.100041+00:00", "level": "ERROR", "message": "exception message\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main_copy.py\", line 35, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "logger": "__main__", "module": "main_copy", "function": "main", "line": 37, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "DEBUG", "message": "debug message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 28, "thread_name": "MainThread", "acdc": "sample line"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "INFO", "message": "info message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 29, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "WARNING", "message": "warning message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 30, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "ERROR", "message": "error message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 31, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "CRITICAL", "message": "critical message", "logger": "__main__", "module": "main_copy", "function": "main", "line": 32, "thread_name": "MainThread"}
{"timestamp": "2025-04-21T02:06:50.547347+00:00", "level": "ERROR", "message": "exception message:\nTraceback (most recent call last):\n  File \"D:\\!wip\\fellerbuncher\\main_copy.py\", line 35, in main\n    1 / 0\n    ~~^~~\nZeroDivisionError: division by zero", "logger": "__main__", "module": "main_copy", "function": "main", "line": 37, "thread_name": "MainThread"}
